# .github/workflows/upload-to-jfrog.yml

name: Upload Artifact to JFrog Artifactory

on:
  push:
    branches: [ "main" ]

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create an artifact to upload
        run: echo "My artifact content" > artifact.txt

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JFROG_URL }}
          JF_USER: ${{ secrets.JFROG_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
        with:
          custom-server-id: my-jfrog-server

      - name: Upload artifact
        run: |
          # This now correctly uploads the "artifact.txt" file created in the step above
          jf rt u "artifact.txt" "amrutha-githubactions-generic-local/"
